#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 12 01:26:58 2021

@author: caiazzo
"""
outputTexFile = "/Users/caiazzo/HEDERA/CODES/XLSform2PDF/output/zni-individuals/f1.tex"
print(" *** writing survey to file " + outputTexFile + " *** ")
fnew = open(outputTexFile,'w')

fnew.write('\\documentclass[12pt,a4paper]{letter}\n')
fnew.write('\\usepackage[utf8]{inputenc}\n')
fnew.write('\\usepackage[spanish]{babel}\n')
fnew.write('\\usepackage[T1]{fontenc}\n')
fnew.write('\\usepackage{graphicx}\n')
fnew.write('\\usepackage[left=.75cm,right=.75cm,top=.5cm,bottom=2.5cm]{geometry}\n')
fnew.write('\\usepackage{multicol}\n')
fnew.write('\\usepackage[table]{xcolor}\n')
fnew.write('\\setlength{\columnsep}{.5cm}\n')

fnew.write('\\usepackage{fancyhdr}\n')
fnew.write('\\pagestyle{fancy}\n')
fnew.write('\\usepackage{multirow}\n')
fnew.write('\\usepackage{babel}\n')
fnew.write('\\usepackage{tabularx}\n')
fnew.write('\\definecolor{mygray}{HTML}{D2D0CF}\n')
fnew.write('\\definecolor{myblue}{HTML}{1F618D}\n')


fnew.write('\\begin{document}\n')
  
fnew.write('\\begin{center}\n')
fnew.write("\\textbf{FORMATO DE VERIFICACI\\'ON DE INSTALACI\\'ON \\ SOLUCI\\'ON FOTOVOLTAICA INDIVIDUAL}\n")
fnew.write('\\end{center}\n')


fnew.write('\\begin{center}\n')


fnew.write('\\scriptsize\n')
fnew.write('\\begin{tabular}{|p{4.3cm}|p{3.2cm}|p{2.6cm}|p{4.5cm}|p{2.4cm}|}\n')

fnew.write('\\hline\n')
fnew.write('\\multicolumn{ 5}{|c|}{\\cellcolor{mygray}\\textbf{  1. DATOS GENERALES}} \\\\ \\hline\n')
fnew.write('Contrato & ... & Fecha de visita & ... & Estado del tiempo \\\\ \\hline\n')
fnew.write('Municipio & ... & Vereda/Localidad &...&...  \\\\ \\hline\n')
fnew.write("Administrador &  \\multicolumn{2}{l|}{...} & Acompa\~namiento de interventor\\'ia SI/NO: &...  \\\\ \\hline\n")
fnew.write("Contratista Ejecutor de obra &  \\multicolumn{2}{l|} {...} & Inventor &...  \\\\ \\hline\n")
fnew.write("Nombre presidente JAC&  \\multicolumn{2}{l|} {...} & Tel\\'efono JAC &...  \\\\ \\hline\n")
fnew.write('\\end{tabular}\n')
fnew.write('\\ \\\\[0.5em]\n')


fnew.write("\\begin{tabular}{|p{3.9cm}|p{4.55cm}|p{4.cm}|p{5cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 4}{|c|}{\\cellcolor{mygray}\\textbf{2. INFORMACI\\'ON DEL BENEFICIARIO}} \\\\ \\hline\n")
fnew.write("\\multicolumn{2}{|l|}{Nombre completo del beneficiario} & \\multicolumn{2}{l|}{...}   \\\\ \\hline\n")
fnew.write("N\\'umero de c\'edula & ... & Tel\\'efono &...  \\\\ \\hline\n")
fnew.write("\\multicolumn{2}{|l|}{?`Con que electrodom\\'esticos cuenta? }& \\multicolumn{2}{l|}{...}   \\\\ \\hline\n")
fnew.write("\\end{tabular} \n")
fnew.write("\\ \\\\[0.5em]\n")

fnew.write("\\begin{tabular}{|p{7.5cm}|p{2.cm}|p{4cm}|p{4cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 4}{|c|}{\\cellcolor{mygray} \\textbf{3. CAPACITACI\'ON}} \\\\ \\hline\n")
fnew.write("?`Fue capacitado en el manejo de los equipos? SI/NO & ... & Quién lo capacito? &...  \\\\ \\hline\n")
fnew.write("?`Cuenta con el manual de usuario? SI/NO & ... & Estado del manual (Bueno, Regular, Malo) &...  \\\\ \\hline\n")
fnew.write("?`Entiende el manual suministrado? SI/NO & ... & Idoma del Manual &...  \\\\ \\hline\n")
fnew.write("\\multicolumn{ 3}{|p{10cm}|}{?`Le informaron sobre quien har\\'a la administraci\\'on y mantenimiento?} & ... \\\\ \\hline\n")
fnew.write("?`Le informaron que el servicio de energ\\'a tiene un costo? & ... & ?`Cual es este costo? & ...   \\\\ \\hline\n")
fnew.write("\\end{tabular} \n")
fnew.write("\\ \\\\[0.5em]\n")


fnew.write("\\begin{tabular}{|p{6cm}|p{6cm}|p{6cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 3}{|c|}{\\cellcolor{mygray} \\textbf{4. INFORMACI\\'ON DE EQUIPOS}} \\\\ \\hline\n")
fnew.write("\\multicolumn{ 3}{|c|}{\\cellcolor{myblue} \\textcolor{white}{4.1. MODULOS FOTOVOLTAICOS}} \\\\ \\hline\n")
fnew.write("Cantidad de modulos: & Potencia por modulo (W):  & Potencia total instalada (W):  \\\\ \\hline\n")
fnew.write(" ... & ...& ... \\\\ \\hline\n")
fnew.write("\\end{tabular} \n")
fnew.write("\n")
fnew.write("\\begin{tabular}{|p{3.3cm}|p{5.5cm}|p{3.25cm}|p{5.5cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multirow{3}{*}{Marca} & ... & \\multirow{3}{*}{Serial} & ...   \\\\\n") 
fnew.write("& ...& &...  \\\\\n")
fnew.write("& ... & & ... \\\\\n")
fnew.write("\\hline\n")
fnew.write("\\end{tabular} \n")
fnew.write("\\ \\\\[0.5em]\n")

fnew.write("\\begin{tabular}{|p{5.6cm}|p{2.75cm}|p{3cm}|p{2.75cm}|p{3cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 2}{|c|}{?`Est\\'an ubicados y orientados correctamente?} &\\multicolumn{ 3}{c|} {...} \\\\ \\hline\n")
fnew.write("Georreferenciaci\\'on & Latitud: & ... & Longitud: & ...  \\\\ \\hline\n")
fnew.write("\\end{tabular}  \n")

fnew.write("\\begin{tabular}{|p{6cm}|p{6cm}|p{6cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 3}{|c|}{\\cellcolor{myblue} \\textcolor{white}{4.2. BANCO DE BATER\\'IAS}} \\\\ \\hline\n")
fnew.write("Cantidad de baterias: & Capacidad por bateria (A/h):  & Capacidad total instalada (A/h):  \\\\ \\hline\n")
fnew.write("... & ...& ... \\\\ \\hline\n")
fnew.write("\\end{tabular} \n")

fnew.write("\\begin{tabular}{|p{3.3cm}|p{5.5cm}|p{3.25cm}|p{5.5cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\\multirow{3}{*}{Marca} & ... & \\multirow{3}{*}{Serial} & ...   \\\\\n") 
fnew.write(" & ...& &...  \\\\\n")
fnew.write(" & ... & & ... \\\\\n")
fnew.write("\\hline\n")
fnew.write("\\end{tabular}\n")  

fnew.write("\\begin{tabular}{|p{2.5cm}|p{6.5cm}|p{2.5cm}|p{6.05cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 4}{|c|}{\\cellcolor{myblue} \\textcolor{white}{4.3. INVERSOR}} \\\\ \\hline\n")
fnew.write("\\multicolumn{ 2}{|l|}{Potencia del inversor (W)} & \\multicolumn{ 2}{l|}{..} \\\\ \\hline\n")
fnew.write(" Marca & ...  & Serial &... \\\\ \\hline\n")
fnew.write("\\end{tabular}\n")

fnew.write("\\begin{tabular}{|p{2.5cm}|p{6.5cm}|p{2.5cm}|p{6.05cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 4}{|c|}{\\cellcolor{myblue} \\textcolor{white}{4.4. CONTROLADOR}} \\\\ \\hline\n")
fnew.write("\\multicolumn{ 2}{|l|}{Capacidad del controlador (A) } & \\multicolumn{ 2}{l|}{...} \\\\ \\hline\n")
fnew.write(" Marca & ...  & Serial &... \\\\ \\hline\n")
fnew.write(" \end{tabular}\n")
fnew.write("\\ \\\\[0.5em]\n")

fnew.write("\\begin{tabular}{|p{9.2cm}|p{9.25cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 2}{|c|}{\\cellcolor{mygray}\\textbf{5. INSTALACI\\'ON EN GENERAL}} \\\\ \\hline\n")
fnew.write(" Inspecci\\'on Visual de la Instalaci\\'on  & Autonom\\'ia seg\\'un el usuario \\\\\n") 
fnew.write(" ... & ... \\\\ \\hline\n")
fnew.write("\\end{tabular} \n")
fnew.write("\\ \\\\[0.5em]\n")

fnew.write("\\newpage\n")
fnew.write("\\begin{tabular}{|p{9.2cm}p{9.25cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 2}{|c|}{\\cellcolor{mygray}\\textbf{6. OBSERVACIONES}} \\\\ \\hline\n")
fnew.write("  &  \\\\ \\hline\n")
fnew.write("\multicolumn{ 2}{|l|}{El ejercicio de esta verificaci\\'on no exime o limita la responsabilidad del contratista e interventor sobre la instalaci\\'on. }\\\\ \\hline\n") 
fnew.write("\\end{tabular}\n") 
fnew.write("\\ \\\\[1em]\n")


fnew.write("\\begin{tabular}{|p{6cm}p{6cm}p{6cm}|}\n")
fnew.write("\\hline\n")
fnew.write("\\multicolumn{ 3}{|c|}{\\cellcolor{mygray} \\textbf{FIRMAS}} \\\\ \\hline\n")
fnew.write("  & &  \\\\ \\hline\n")
fnew.write("\\end{tabular} \n")
fnew.write("\\ \\\\[0.5em]\n")

fnew.write("\\begin{flushleft}\n")
fnew.write("\\begin{minipage}[t]{0.3\\textwidth}\n")
fnew.write("IPSE \\\\\n")
fnew.write("Nombre\n")
fnew.write("\\end{minipage}\n")
fnew.write("\\begin{minipage}[t]{0.3\\textwidth}\n")
fnew.write("MME\\\\\n")
fnew.write("Nombre\n")
fnew.write("\\end{minipage}\n")
fnew.write("\\begin{minipage}[t]{0.3\\textwidth}\n")
fnew.write("Contratista\\\\\n")
fnew.write("Nombre\n")
fnew.write("\\end{minipage}\n")
fnew.write("\\ \\\\[0.5em]\n")
fnew.write("\\begin{minipage}[t]{0.3\\textwidth}\n")
fnew.write("Interventor\\'ia\\\\\n")
fnew.write("Nombre\n")
fnew.write("\\end{minipage}\n")
fnew.write("\\begin{minipage}[t]{0.3\\textwidth}\n")
fnew.write("Beneficiario\\\\\n")
fnew.write("Nombre\n")
fnew.write("\\end{minipage}\n")
fnew.write("\\end{flushleft}\n")
fnew.write("\\end{center}\n")

fnew.write('\\end{document}')
fnew.close()